rango/urls.py
from django.conf.urls import url

from . import views

app_name = 'rango'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    # url(r'^register$', views.register, name='register'),
    # url(r'^login$', views.user_login, name='login'),
    # url(r'^logout$', views.user_logout, name='logout'),
    url(r'^register_profile/$', views.register_profile, name='register_profile'),
    url(r'^profile/(?P<username>[\w\-]+)/$', views.profile, name='profile'),
    url(r'^list_profiles/$', views.list_profiles, name='list_profiles'),
    url(r'^search/$', views.search, name='search'),
    url(r'^goto/(?P<page_id>\d+)$', views.track_url, name='goto'),
    url(r'^suggest/$', views.category_suggestion, name='category_suggestion'),
    url(r'^add/$', views.auto_add_page, name='auto_add_page'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.show_category, name='show_category'),
    url(r'^like/$', views.like_category, name='like_category'),
]

tango_with_django_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView

from . import views


class MyRegistrationView(RegistrationView):

    def get_success_url(self, user):
        return '/rango/register_profile'


urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^rango/', include('rango.urls')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class Category(models.Model):
    max_length = 128
    name = models.CharField(max_length=max_length, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)
    user_likes = models.ManyToManyField(User, blank=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)


class Page(models.Model):
    max_length = 128
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=max_length)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    # The additional attributes
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Category, Page, UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Category.max_length, help_text='Please enter the category name.')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        # Provide an association between ModelForm and a model
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=Page.max_length, help_text='Please enter the title of the page.')
    url = forms.CharField(max_length=200, help_text='Please enter the URL of the page.')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

        return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
import django
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from datetime import datetime

from .models import Category, Page, UserProfile
from .forms import CategoryForm, PageForm, UserForm, UserProfileForm
from .bing_search import bing_web_search
from .webhouse_search import webhoseio_search


def index(request):
    request.session.set_test_cookie()

    context_dict = {}

    # Query a list of categories and pages from my database.
    # Sort them by likes and show 5 or less

    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]

    visitor_cookie_handler(request)

    context_dict['boldmessage'] = 'Hello from Ivan'
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list
    context_dict['visits'] = request.session['visits']

    response = render(request, 'rango/index.html', context=context_dict)
    return response


# Not a view. Just a helper function

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie, '%Y-%m-%d %H:%M:%S.%f')

    print((datetime.now() - last_visit_time))
    print((datetime.now() - last_visit_time).seconds)
    if(datetime.now() - last_visit_time).seconds > 10:
        visits += 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits


# Not a view. Just a helper function

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)

    if not val:
        val = default_val

    return val


@login_required
def add_category(request):

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)
    else:
        form = CategoryForm()

    return render(request, 'rango/add_category.html', {'form': form})


@login_required
def add_page(request, category_name_slug):

    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request, category_name_slug)
        else:
            print(form.errors)
    else:
        form = PageForm()

    context_dict = {'form': form, 'category': category}

    return render(request, 'rango/add_page.html', context_dict)


@login_required
def auto_add_page(request):
    context_dict = {}

    if request.method == 'GET':
        cat_id = request.GET['category_id']
        url = request.GET['url']
        title = request.GET['title']

        cat = Category.objects.get(id=int(cat_id))
        if cat:
            page = Page.objects.get_or_create(category=cat, title=title, url=url, views=0)[0]
            page.save()

    page_list = Page.objects.filter(category=cat).order_by('-views')
    context_dict['pages'] = page_list

    return render(request, 'rango/page_list.html', context=context_dict)


def show_category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category).order_by('-views')

        context_dict['pages'] = pages
        context_dict['category'] = category

    except Category.DoesNotExist:
        context_dict['pages'] = None
        context_dict['category'] = None

    if request.method == 'POST':
        if request.POST.get('bing_query'):
            bing_query = request.POST['bing_query'].strip()
            if bing_query:
                bing_result_list = bing_web_search(bing_query)
                context_dict['bing_result_list'] = bing_result_list
                context_dict['bing_query'] = bing_query

    return render(request, 'rango/category.html', context=context_dict)


@login_required
def like_category(request):
    cat_id = None
    likes = 0

    if request.method == 'GET':
        cat_id = request.GET['category_id']

    if cat_id:
        cat = Category.objects.get(id=int(cat_id))
        likes = cat.likes
        if cat and not Category.objects.filter(user_likes=request.user, id=int(cat_id)):
            cat.user_likes.add(request.user)
            likes += 1
            cat.likes = likes
            cat.save()

    return HttpResponse(likes)


def get_category_list(max_result=0, starts_with=''):
    cat_list = []

    if starts_with:
        cat_list = Category.objects.filter(name__istartswith=starts_with)
    if max_result > 0:
        if len(cat_list) > max_result:
            cat_list = cat_list[:max_result]

    return cat_list


def category_suggestion(request):
    cat_list = []

    if request.method == 'GET':
        starts_with = request.GET['suggestion']
        cat_list = get_category_list(8, starts_with)

    return render(request, 'rango/cats.html', {'cats': cat_list})


def track_url(request, page_id):

    try:
        page = Page.objects.get(id=page_id)
        if page:
            page.views += 1
            page.save()
            return redirect(page.url)
    except:
        print('There is no such page!')

    return redirect(reverse('rango:index'))


# def register(request):
#     context_dict = {}
#     registered = False
#
#     if request.method == 'POST':
#         user_form = UserForm(data=request.POST)
#         profile_form = UserProfileForm(data=request.POST)
#
#         if user_form.is_valid() and profile_form.is_valid():
#             user = user_form.save()
#             user.set_password(user.password)
#             user.save()
#
#             profile = profile_form.save(commit=False)
#             profile.user = user
#
#             if 'picture' in request.FILES:
#                 profile.picture = request.FILES['picture']
#
#             profile.save()
#             registered = True
#         else:
#             print(user_form.errors, profile_form.errors)
#     else:
#         user_form = UserForm()
#         profile_form = UserProfileForm()
#
#     context_dict['user_form'] = user_form
#     context_dict['profile_form'] = profile_form
#     context_dict['registered'] = registered
#
#     return render(request, 'rango/register.html', context=context_dict)
#
#
# def user_login(request):
#
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         password = request.POST.get('password')
#
#         user = authenticate(username=username, password=password)
#
#         if user:
#             if user.is_active:
#                 login(request, user)
#                 return HttpResponseRedirect(reverse('rango:index'))
#             else:
#                 return HttpResponse("You Rango account is disabled")
#         else:
#             print('Invalid login details: {0}, {1}'.format(username, password))
#             return HttpResponse('Invalid login details')
#     else:
#         return render(request, 'rango/login.html', {})
#
#
# @login_required
# def user_logout(request):
#     logout(request)
#     return HttpResponseRedirect(reverse('rango:index'))


@login_required
def register_profile(request):
    context_dict = {}

    if request.method == 'POST':
        profile_form = UserProfileForm(data=request.POST)

        if profile_form.is_valid():
            try:
                profile_user = request.user.userprofile
            except UserProfile.DoesNotExist:
                profile_user = UserProfile(user=request.user)

            profile_user.user = request.user

            if 'website' in request.POST:
                profile_user.website = request.POST['website']

            if 'picture' in request.FILES:
                profile_user.picture = request.FILES['picture']
            else:
                profile_user.picture = None

            profile_user.save()

            return redirect(reverse('rango:index'))
        else:
            print(profile_form.errors)
    else:
        profile_form = UserProfileForm()

    context_dict['profile_form'] = profile_form

    return render(request, 'registration/profile_registration.html', context=context_dict)


@login_required
def profile(request, username):
    context_dict = {'username': username}

    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        return redirect(reverse('rango:index'))

    profile_user = UserProfile.objects.get_or_create(user=user)[0]
    context_dict['profile'] = profile_user

    if request.method == 'POST':
        return redirect(reverse('rango:register_profile'))

    return render(request, 'rango/profile.html', context=context_dict)


@login_required
def list_profiles(request):
    context_dict = {}
    profile_list = []

    for user in User.objects.all():
        try:
            if user.userprofile:
                profile_list.append(user.userprofile)
        except UserProfile.DoesNotExist:
            print('There is no profile for ' + str(user))

    context_dict['profile_list'] = profile_list

    return render(request, 'rango/list_profiles.html', context=context_dict)


def search(request):
    context_dict = Context.load_context_dict()

    if request.method == 'POST':
        if request.POST.get('bing_query'):

templates/rango/about.html
{% extends "rango/base.html" %}

{% load staticfiles %}

{% block title_block %}
    About
{% endblock title_block %}

{% block body_block %}
    <div>
        <h1>This tutorial has been put together by Ivan</h1> <br/>
        <h2>{{ project }}</h2>
    </div>
    <div>
        <!-- Images -->
        <img src="{{ MEDIA_URL }}tiger.jpg" alt="Picture of tiger" /><br/>
        <!-- Number of visits -->
        Number of visits: {{ visits }}<br/>
        <!-- JQuery block -->
        <button class="btn" onclick="alert('You clicked JQuery button!')">
            JQuery Example Default
        </button>
        <button class="btn ouch" id="about_btn">
            JQuery Example Custom
        </button>
        <h4 class="ouch">This is one more example</h4>
    </div>
{% endblock body_block %}

templates/rango/add_category.html
{% extends "rango/base.html" %}

{% load staticfiles %}
{% load bootstrap_toolkit %}

{% block title_block %}
    Add a new Category
{% endblock title_block %}

{% block body_block %}
    <div>
        <form role="form" id="category_form" method="post" action="{% url 'rango:add_category' %}">
            <h2 class="form-signin-heading">Add a Category</h2>
            {% csrf_token %}

            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                <div>
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
                </div>
            {% endfor %}
            <button class="btn btn-primary" type="submit" name="submit">Create Category</button>
        </form>
    </div>
{% endblock body_block %}

templates/rango/add_page.html
{% extends "rango/base.html" %}

{% load staticfiles %}

{% block title_block %}
    {{ category.name }}. Add a new Page.
{% endblock title_block %}

{% block body_block %}
    {% if category %}
        <div>
            <form role="form" id="page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
                <h2 class="form-signin-heading">Add a Page to
                    <a href="/rango/category/{{ category.slug }}">{{ category.name }}</a></h2>
                {% csrf_token %}

                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    <div>
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}
                    </div>
                {% endfor %}
                <br/>
                <button class="btn btn-primary" type="submit" name="submit">Add Page</button>
            </form>
        </div>
    {% else %}
        <h1>A category by this name doesn't exist!</h1><br/>
    {% endif %}
{% endblock body_block %}

templates/rango/base.html
{% extends 'rango/base_bootstrap.html' %}

{#<!DOCTYPE html>#}
{##}
{#{% load staticfiles %}#}
{#{% load rango_template_tags %}#}
{##}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Rango -#}
{#        {% block title_block %}#}
{#            How to tango with Django#}
{#        {% endblock title_block %}#}
{#    </title>#}
{#</head>#}
{##}
{#<body>#}
{#    <div>#}
{#        {% block sidebar_block %}#}
{#            {% get_category_list category%}#}
{#        {% endblock sidebar_block %}#}
{#    </div>#}
{##}
{#    <div>#}
{#        {% block body_block %}#}
{#        {% endblock %}#}
{#    </div>#}
{#    <hr/>#}
{#    <div>#}
{#        <ul>#}
{#            {% if user.is_authenticated %}#}
{#                <li><a href="{% url 'rango:add_category' %}">Add a new Category</a></li>#}
{#            {% endif %}#}
{#            <li><a href="{% url 'rango:about' %}">About</a></li>#}
{#            <li><a href="{% url 'rango:index' %}">Index</a></li>#}
{#            {% if user.is_authenticated %}#}
{#                <li><a href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>#}
{#                <li><a href="{% url 'auth_password_change' %}">Change Password</a></li>#}
{#            {% else %}#}
{#                <li><a href="{% url 'auth_login' %}">Sign in</a></li>#}
{#                <li><a href="{% url 'registration_register' %}">Sign Up</a></li>#}
{#            {% endif %}#}
{#        </ul>#}
{#    </div>#}
{#</body>#}
{#</html>#}

templates/rango/base_bootstrap.html
<!DOCTYPE html>

{% load staticfiles %}
{% load rango_template_tags %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

      <title>Rango - {% block title %}How to Tango with Django!{% endblock %}</title>
      <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">

  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up"
              type="button"
              data-toggle="collapse"
              data-target="#navbar"
              aria-controls="navbar"
              aria-expanded="false"
              aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'rango:index' %}">Rango</a>

      <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'rango:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:add_category' %}">Add Category</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:search' %}">Search</a>
          </li>
          {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:profile' user.username %}">Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:list_profiles' %}">List Profiles</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_password_change' %}">Change Password</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_logout' %}">Logout</a>
              </li>
          {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_login' %}">Sign in</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'registration_register' %}">Sign up</a>
              </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container-fluid">
        <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <div class="col-lg-12">
                <h4>Type to find a category</h4>
                <form>
                    <input class="form-control" type="text" size="30"
                           name="suggestion" value="" id="suggestion" />
                </form>
                <hr/>
            </div>
            <div id="cats">
                {% block sidebar_block %}
                    {% get_category_list category %}
                {% endblock %}
            </div>
        </div>
        <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 main">
        <br/>
            {% block body_block %}{% endblock %}
        </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script
        src="https://code.jquery.com/jquery-3.1.1.slim.min.js"
        integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n"
        crossorigin="anonymous">
    </script>

    <script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
{#    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>#}
    <script src="{% static 'js/rango-jquery.js' %}"></script>
    <script src="{% static 'js/rango-ajax.js' %}"></script>
  </body>
</html>

templates/rango/category.html
{% extends "rango/base.html" %}

{% load staticfiles %}
{% load rango_template_tags %}

{% block title_block %}
    {{ category.name }}
{% endblock title_block %}

{% block body_block %}
    <h1>{{ category.name }}</h1>
    <div>
        <strong id="id_count">{{ category.likes }}</strong> people likes this category
        {% if user.is_authenticated %}
            <button class="btn btn-primary" data-cat-id="{{ category.id }}"
                    id="like" type="button">
                Like
            </button>
        {% endif %}
    </div>
    {% if category %}
        <div id="pages">
            {% get_page_list pages %}
        </div>
        {% if user.is_authenticated %}
            <a href="{% url 'rango:add_page' category.slug %}">Add a new Page</a><br/>
        {% endif %}
        {% else %}
        <h1>The specified category doesn't exist!</h1>
    {% endif %}

    <div>
        <br/>
        {% if user.is_authenticated %}
            <h2>Search pages with Bing</h2>
            {% get_search_api bing_query bing_result_list 'bing' 'rango:show_category' category.slug %}
        {% endif %}
    </div>
{% endblock body_block %}

templates/rango/cats.html
<div class="row marketing main offset-sm-1">
<ul>
{% if cats.exists %}
    {% for c in cats %}
        {% if c == act_cat %}
            <li class="nav-item">
                <strong>
                    <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
                </strong>
            </li>
        {% else %}
            <li class="nav-item">
                <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
            </li>
        {% endif %}
    {% endfor %}
{% else %}
    There are no categories present.
{% endif %}
</ul>
</div>

templates/rango/index.html
{% extends "rango/base.html" %}

{% load staticfiles %}

{% block body_block %}
    <div class="jumbotron">
        <h1>Rango says...</h1>
        <div>
        {% if user.is_authenticated %}
            howdy {{ user.username }}<br/>
        {% else %}
            hey there partner! <br/>
        {% endif %}
        </div>
    </div>

    <div class="row marketing">
        <div class="col-lg-6 list-group">
        <div>
            {% if categories.exists %}
            <h1>Most liked Categories</h1>
            <ul>
                {% for category in categories %}
                    <li class="list-group-item">
                        <a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
                        <p class="offset-xs-1 badge badge-pill badge-primary">{{ category.likes }}</p>
                    </li>
                {% endfor %}
            </ul>
            {% else %}
                <strong>There are not categories present</strong>
            {% endif %}
        </div>
        </div>
        <div class="col-lg-6 list-group">
        <div>
            {% if pages.exists %}
            <h1>Most viewed Pages</h1>
            <ul>
                {% for page in pages %}
                    <li class="list-group-item">
                        <a href="{% url 'rango:goto' page.id %}">{{ page.title }}</a>
                        <p class="offset-xs-1 badge badge-pill badge-primary">{{ page.views }}</p>
                    </li>
                {% endfor %}
            </ul>
                {% else %}
                <strong>There are not pages present</strong>
            {% endif %}
        </div>
        </div>
    </div>


    <div>
       <img src="{% static "images/rango.jpg" %}" alt="Picture of Rango" />
   </div>
{% endblock body_block %}

templates/rango/list_profiles.html
{% extends 'rango/base.html' %}

{% load staticfiles %}

{% block title_block %}
    Profiles
{% endblock title_block %}

{% block body_block %}
    <h2 class="form-signin-heading">User Profiles</h2>
     <div class="panel-heading">
        <!-- Display search results in an ordered list -->
        <div class="panel-body">
        <div class="list-group">
        {% for profile in profile_list %}
            <div class="list-group-item">
            {% if profile.picture %}
                <img src="{{ MEDIA_URL }}{{ profile.picture }}"
                     width="64" height="64"
                     alt="{{ profile.user.username }} profile picture" />
            {% else %}
                <img src="http://lorempixel.com/64/64/people/"
                     width="64" height="64"
                     alt="{{ profile.user.username }} profile picture" />
            {% endif %}
            <h4 class="col-sm-1 list-group-item-heading">
                <a href="{% url 'rango:profile' profile.user.username %}">{{ profile.user.username }}</a>
            </h4>
            </div>
        {% endfor %}
        </div>
        </div>
    </div>
{% endblock body_block %}

templates/rango/login.html
{% extends "rango/base.html" %}

{% load staticfiles %}

{% block title_block %}
    Login
{% endblock title_block %}

{% block body_block %}
    <h1>Login to Rango</h1>
    <div>
        <form id="login_form" method="post" action="{% url 'rango:login' %}">
            {% csrf_token %}

            Username: <input type="text" name="username" value="" size="50" /><br/>
            Password <input type="password" name="password" value="" size="50" /><br/>

            <input type="submit" name="submit", value="Login" />
        </form>
    </div>
{% endblock body_block %}

templates/rango/page_list.html
<h1>Pages</h1>
{% if pages.exists %}
<ul>
{% for page in pages %}
    <li>
        <a href="{% url 'rango:goto' page.id %}">{{ page.title }}</a>
        <strong id="view_count">{{ page.views }}</strong>
    </li>
{% endfor %}
</ul>
{% else %}
<strong>No pages currently in category</strong><br/>
{% endif %}

templates/rango/register.html
{% extends "rango/base.html" %}

{% load staticfiles %}

{% block title_block %}
    Register
{% endblock title_block %}

{% block body_block %}
    <h1>Register for Rango</h1>
    {% if registered %}
        Rango says: <strong>Thank you for registration!</strong>
        <a href="{% url 'rango:index' %}">Back to the main page</a>
    {% else %}
        Rango says: <strong>Register here!</strong>
        <div>
            <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
                {% csrf_token %}

                {{ user_form.as_p }}
                {{ profile_form.as_p }}

                <input type="submit" name="submit", value="Register" />
            </form>
        </div>
    {% endif %}
{% endblock body_block %}

templates/rango/search.html
{% extends 'rango/base.html' %}

{% load staticfiles %}
{% load rango_template_tags %}

{% block title_block %}
    Search
{% endblock title_block %}

{% block body_block %}
<div>
    <h1>Search with Rango</h1><br/>
    <div class="container-fluid">
        <div class="row">
        <div class="col-lg-5 main">
            <div>
                <h2>Bing Search</h2><br/>
                {% get_search_api bing_query bing_result_list 'bing' 'rango:search' %}
            </div>
        </div>
        <div class="col-lg-5 main">
            <div>
                <h2>WebHose.io Search</h2><br/>
                {% get_search_api webhoseio_query webhoseio_result_list 'webhoseio' 'rango:search' %}
            </div>
        </div>
        </div>
    </div>
</div>
{% endblock %}